{
 "title": "dbquery_exporter",
 "tags": [
  "prometheus",
  "db"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dbquery_exporter_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dbquery_exporter_build_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - dbquery_exporter_start_time{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Configuration age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - dbquery_exporter_configuration_load_time{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Query duration [99%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(dbquery_exporter_query_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{database}}/{{query}}"
    }
   ]
  },
  {
   "title": "Queries / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_query_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{database}}/{{query}}"
    }
   ]
  },
  {
   "title": "Cache hit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dbquery_exporter_cache_hit_total{instance=\"$instance\"} / (dbquery_exporter_cache_hit_total{instance=\"$instance\"} + dbquery_exporter_cache_miss_total{instance=\"$instance\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DB errors  / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_query_database_errors_total{instance=\"$instance\"}[$__rate_interval]) or vector(0)",
     "legendFormat": "{{database}}/{{query}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{database}}/{{query}}"
    }
   ]
  },
  {
   "title": "Requests duration [99%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(dbquery_exporter_request_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "99 {{handler}}"
    }
   ]
  },
  {
   "title": "Queue wait duration [99%]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(dbquery_exporter_tasks_queue_wait_time_seconds_bucket{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{loader}}"
    }
   ]
  },
  {
   "title": "Processing errors  / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_process_errors_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "Loaders & pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(dbquery_exporter_dbpool_activeconnections{instance=\"$instance\"})",
     "legendFormat": "active connections"
    },
    {
     "expr": "sum(dbquery_exporter_dbpool_idleconnections{instance=\"$instance\"})",
     "legendFormat": "idle conenctions"
    }
   ]
  },
  {
   "title": "Connections /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(dbquery_exporter_dbpool_connections_connected_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "opened"
    },
    {
     "expr": "sum(rate(dbquery_exporter_dbpool_connections_failed_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Connections waiting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "dbquery_exporter_dbpool_connections_wait_total{instance=\"$instance\"}",
     "legendFormat": "connection waiting"
    }
   ]
  },
  {
   "title": "Connections wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "increase(dbquery_exporter_dbpool_connections_wait_second{instance=\"$instance\"}[5m]) or vector(0)",
     "legendFormat": "connection wait time"
    }
   ]
  },
  {
   "title": "Loaders in pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "dbquery_exporter_loaders_in_pool{instance=\"$instance\"}",
     "legendFormat": "Loaders in pool"
    }
   ]
  },
  {
   "title": "created workers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_workers_created_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{loader}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_process_errors_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Scheduled tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_task_scheduled_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}