{
 "title": "dbquery_exporter",
 "tags": [
  "prometheus",
  "db"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dbquery_exporter_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dbquery_exporter_build_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_query_duration_seconds_sum{instance=\"$instance\"}[5m])",
     "legendFormat": "{{database}}/{{query}}"
    }
   ]
  },
  {
   "title": "Queries / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_query_duration_seconds_count{instance=\"$instance\"}[5m])",
     "legendFormat": "{{database}}/{{query}}"
    }
   ]
  },
  {
   "title": "Cache hit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dbquery_exporter_query_cache_hit{instance=\"$instance\"} / sum by (instance, job) (dbquery_exporter_query_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "DB errors  / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_query_database_errors_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{database}}/{{query}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_request_duration_seconds_count{instance=\"$instance\"}[5m])",
     "legendFormat": "{{database}}/{{query}}"
    }
   ]
  },
  {
   "title": "Requests duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_request_duration_seconds_sum{instance=\"$instance\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Processing errors  / s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_process_errors_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  { "title": "Loaders & pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dbquery_exporter_dbpool_activeconnections{instance=\"$instance\"}",
     "legendFormat": "active connections"
    },
    {
     "expr": "dbquery_exporter_dbpool_idleconnections{instance=\"$instance\"}",
     "legendFormat": "idle conenctions"
    }
   ]
  },
  {
   "title": "Connections /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(dbquery_exporter_dbpool_connections_connected{instance=\"$instance\"}[5m])",
     "legendFormat": "opened"
    },
    {
     "expr": "rate(dbquery_exporter_dbpool_connections_failed{instance=\"$instance\"}[5m])",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Connections waiting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "dbquery_exporter_dbpool_connections_waitcount{instance=\"$instance\"}",
     "legendFormat": "connection waiting"
    }
   ]
  },
  {
   "title": "Connections wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "increase(dbquery_exporter_dbpool_connections_wait_second{instance=\"$instance\"}[5m])",
     "legendFormat": "connection wait time"
    }
   ]
  },
  {
   "title": "Loaders in pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "dbquery_exporter_loaders_in_pool{instance=\"$instance\"}",
     "legendFormat": "Loaders in pool"
    }
   ]
  }
 ]
}